Allow Rails 8.1 and edge (#16)

diff --git a/.github/workflows/tests.yml b/.github/workflows/tests.yml
--- a/.github/workflows/tests.yml
+++ b/.github/workflows/tests.yml
@@ -7,16 +7,28 @@ on:
     branches: [ main ]
 
 jobs:
-  test:
+  matrix-test:
     runs-on: ubuntu-latest
+    strategy:
+      fail-fast: false
+      matrix:
+        gemfile:
+          - gemfiles/rails_7_2.gemfile
+          - gemfiles/rails_8_0.gemfile
+          - gemfiles/rails_8_1.gemfile
+          - gemfiles/rails_edge.gemfile
+    continue-on-error: ${{ matrix.gemfile == 'gemfiles/rails_edge.gemfile' }}
+
+    env:
+      BUNDLE_GEMFILE: ${{ github.workspace }}/${{ matrix.gemfile }}
 
     steps:
       - uses: actions/checkout@v4
 
       - name: Set up Ruby and Bundler
-        uses: ruby/setup-ruby@v1.196.0
+        uses: ruby/setup-ruby@v1
         with:
-          ruby-version: 3.3.4
+          ruby-version: 4.0.1
           bundler-cache: true
 
       - name: Setup pre-commit and run linters
@@ -24,3 +36,19 @@ jobs:
 
       - name: Run tests
         run: bin/rspec
+
+  test:
+    needs: matrix-test
+    runs-on: ubuntu-latest
+    if: always()
+    steps:
+      - name: Check status
+        run: |
+          RESULT="${{ needs.matrix-test.result }}"
+          if [ "$RESULT" == "success" ] || [ "$RESULT" == "skipped" ]; then
+            echo "All required tests passed!"
+            exit 0
+          else
+            echo "Required tests failed."
+            exit 1
+          fi
